import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Nav";
import Works from "../components/Works";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Richard Kwon - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Works />
      <About />
      <Footer />
    </div>
  );
};

export default Home;
